### ISSUE TITLE
Wrong date in post in lastest news

### ISSUE THREAD

**Issue by tomasz-biernacki** [Lambda-X/lambdax-web#77]
<img width="545" alt="screen shot 2016-03-03 at 19 45 13" src="https://cloud.githubusercontent.com/assets/15321488/13506683/909f1be4-e17f-11e5-9825-7b5d4ccf7788.png">

But should be the **23th**.

**Comment by arichiardi** [comment]
I investigated this a bit and it looks like it is the backend who has a problem (see `:date` field here):

```
{:text "RT @richiardiandrea: (conj [] 'lisp 'practicality) ;;=&gt; ['clojure can do it]. https://t.co/kWe1UYRSwg Good job @DavidYKay!", :link "#clojure", :title "TWITTER NEWS!", :date #inst "2016-04-21T00:32:21.000-00:00", :type :tweet, :img {:src "img/news.png", :alt "news"}, :author "@lambdax_io"}
```

**Comment by arichiardi** [comment]
No I take it back, the `#inst` is correct, and matches the server...on the client the conversion is not right when we display.

**Comment by arichiardi** [comment]
Ok the problem is that the website displays the date in UTC, so I don't think we can fix that unless we do some timezone trick.

For instance, the Tweet "RT @richiardiandrea: (conj [] 'lisp 'practicality) ..." was published on `5:24 PM - 20 Apr 2016` according to Tweeter but UTC is `2016-04-21T00:32:21.000Z`.

So what we display? The day is 21, but for Tweeter is 20 (here where I am located, but probably not where you guys are located).

Shall we leave it UTC anyways? @tomasz-biernacki @dstiberova

**Comment by tomasz-biernacki** [comment]
IMO should be local time, hence 20 April for your post, not 21.

**Comment by tomasz-biernacki** [comment]
Plus, the links are still not working, see https://github.com/Lambda-X/lambdax-web/issues/76

**Comment by arichiardi** [comment]
Agree about the timezone, the new patch will do the following:

![selection_001](https://cloud.githubusercontent.com/assets/1724788/14718037/30df4ba2-07a9-11e6-85a2-62051225fd94.png)

![selection_002](https://cloud.githubusercontent.com/assets/1724788/14718041/35024018-07a9-11e6-9ec2-00483dac2961.png)
